name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
  
  deploy:
    if: ${{ github.event_name == 'push' }}
    needs: build
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ""
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          justlogin: true
      - run: |
          cd 5HeadBot
          heroku container:login
          heroku container:push worker -a ${{secrets.HEROKU_APP_NAME}}
          heroku container:release worker -a ${{secrets.HEROKU_APP_NAME}}
